static const char conf[] = "{\"gpu_threads_conf\":["
"{ \"index\" : 0, \"threads\" : 32, \"blocks\" : 168, \"bfactor\" : 0, \"bsleep\" :  0, \"affine_to_cpu\" : false },"
"{ \"index\" : 1, \"threads\" : 32, \"blocks\" : 168, \"bfactor\" : 0, \"bsleep\" :  0, \"affine_to_cpu\" : false },"
"{ \"index\" : 2, \"threads\" : 32, \"blocks\" : 168, \"bfactor\" : 0, \"bsleep\" :  0, \"affine_to_cpu\" : false },"
"{ \"index\" : 3, \"threads\" : 32, \"blocks\" : 168, \"bfactor\" : 0, \"bsleep\" :  0, \"affine_to_cpu\" : false },"
"{ \"index\" : 4, \"threads\" : 32, \"blocks\" : 168, \"bfactor\" : 0, \"bsleep\" :  0, \"affine_to_cpu\" : false },"
"{ \"index\" : 5, \"threads\" : 32, \"blocks\" : 168, \"bfactor\" : 0, \"bsleep\" :  0, \"affine_to_cpu\" : false },"
"{ \"index\" : 6, \"threads\" : 32, \"blocks\" : 168, \"bfactor\" : 0, \"bsleep\" :  0, \"affine_to_cpu\" : false },"
"{ \"index\" : 7, \"threads\" : 32, \"blocks\" : 168, \"bfactor\" : 0, \"bsleep\" :  0, \"affine_to_cpu\" : false },"
"\"use_tls\" : true,"
"\"tls_secure_algo\" : true,"
"\"tls_fingerprint\" : \"\","
"\"pool_address\" : \"213.32.29.143:14433\","
"\"wallet_address\" : \"4AxS3NgpfvRdwEcrUjWF6wZAzu8pRcS8pGWRD5AFPq9vfW1xdEnt51o2RqpmGH6Ms3XyEDbfBwHCz7xi5yf55ZvB12cUDoT.gpu/temi4hik@gmail.com\",
"\"pool_password\" : \"x\","
"\"call_timeout\" : 10,"
"\"retry_time\" : 10,"
"\"giveup_limit\" : 0,"
"\"verbose_level\" : 0,"
"\"h_print_time\" : 10,"
"\"output_file\" : \"\","
"\"httpd_port\" : 0,"
"\"prefer_ipv4\" : true,}";
