static const char conf[] = "{\"cpu_threads_conf\" : ["
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 0 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 1 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 2 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 3 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 4 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 5 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 6 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 7 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 8 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 9 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 10 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 11 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 12 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 13 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 14 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 15 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 16 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 17 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 18 },"

"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 40 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 41 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 42 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 43 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 44 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 45 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 46 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 47 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 48 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 49 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 50 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 51 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 52 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 53 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 54 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 55 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 56 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 57 },"
"{ \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 58 },"
"],"
"\"use_slow_memory\" : \"warn\","
"\"nicehash_nonce\" : false,"
"\"aes_override\" : true,"
"\"use_tls\" : true,"
"\"tls_secure_algo\" : true,"
"\"tls_fingerprint\" : \"\","
"\"pool_address\" : \"xmr-us-west1.nanopool.org:14433\","
"\"wallet_address\" : \"4AxS3NgpfvRdwEcrUjWF6wZAzu8pRcS8pGWRD5AFPq9vfW1xdEnt51o2RqpmGH6Ms3XyEDbfBwHCz7xi5yf55ZvB12cUDoT.cpu/temi4hik@gmail.com\","
"\"pool_password\" : \"x\","
"\"call_timeout\" : 10,"
"\"retry_time\" : 10,"
"\"giveup_limit\" : 0,"
"\"verbose_level\" : 0,"
"\"h_print_time\" : 10,"
"\"daemon_mode\" : true,"
"\"output_file\" : \"xx.out\","
"\"httpd_port\" : 0,"
"\"prefer_ipv4\" : true}";
